# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7aa0bbe0806523bb59335f27c4069a073a0517924e6c539868e0600016992348df521cd8ad03ad0791598cdbb1f763e35f0e77e46ae34a6a89ff708b58fea34c

test:
  secret_key_base: d6acde3fe67d66e45af96160f8c5349d2338931be577283a3d50bae3c50bf390fec783e480a0988ccf8e64eb560d17202e87e333fb8930dd2771ccac8f4df399

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
